#!/usr/bin/env bash
if [ -e Maps ] 
then 
rm -rf /var/www/html/0C3S4s/maps/*
cp -vr Maps /var/www/html/0C3S4s/maps
fi

if [ -e Tilesets ] 
then cp -vr Tilesets /var/www/html/0C3S4s/tilesets 
fi

if [ -e index.pti ] 
then cp -v index.pti /var/www/html/0C3S4s/maps/index.pti 
fi

if [ -e pawnserv.conf ] 
then cp -v pawnserv.conf /var/www/html/0C3S4s/maps/pawnserv.conf 
fi